///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace HealthPort_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the HealthPort_E2ERepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("b6176e85-0426-4858-be4e-6439b2858dd9")]
    public partial class HealthPort_E2ERepository : RepoGenBaseFolder
    {
        static HealthPort_E2ERepository instance = new HealthPort_E2ERepository();
        HealthPort_E2ERepositoryFolders.HealthPort_e2eAppFolder _healthport_e2e;
        HealthPort_E2ERepositoryFolders.BookingFolder _booking;

        /// <summary>
        /// Gets the singleton class instance representing the HealthPort_E2ERepository element repository.
        /// </summary>
        [RepositoryFolder("b6176e85-0426-4858-be4e-6439b2858dd9")]
        public static HealthPort_E2ERepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public HealthPort_E2ERepository() 
            : base("HealthPort_E2ERepository", "/", null, 0, false, "b6176e85-0426-4858-be4e-6439b2858dd9", ".\\RepositoryImages\\HealthPort_E2ERepositoryb6176e85.rximgres")
        {
            _healthport_e2e = new HealthPort_E2ERepositoryFolders.HealthPort_e2eAppFolder(this);
            _booking = new HealthPort_E2ERepositoryFolders.BookingFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("b6176e85-0426-4858-be4e-6439b2858dd9")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The HealthPort_e2e folder.
        /// </summary>
        [RepositoryFolder("e93ace6d-0b2d-4682-9078-8960374539bd")]
        public virtual HealthPort_E2ERepositoryFolders.HealthPort_e2eAppFolder HealthPort_e2e
        {
            get { return _healthport_e2e; }
        }

        /// <summary>
        /// The Booking folder.
        /// </summary>
        [RepositoryFolder("63b8993f-1475-484b-8fbf-b266185b278a")]
        public virtual HealthPort_E2ERepositoryFolders.BookingFolder Booking
        {
            get { return _booking; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class HealthPort_E2ERepositoryFolders
    {
        /// <summary>
        /// The HealthPort_e2eAppFolder folder.
        /// </summary>
        [RepositoryFolder("e93ace6d-0b2d-4682-9078-8960374539bd")]
        public partial class HealthPort_e2eAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fnlnInfo;
            RepoItemInfo _claimInfo;
            RepoItemInfo _phonenumberInfo;
            RepoItemInfo _emailInfo;
            RepoItemInfo _claimdetailsInfo;
            RepoItemInfo _inputtagageInfo;
            RepoItemInfo _priceusdInfo;
            RepoItemInfo _priceuahInfo;

            /// <summary>
            /// Creates a new HealthPort_e2e  folder.
            /// </summary>
            public HealthPort_e2eAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HealthPort_e2e", "/dom[@domain='192.168.56.3:5044']", parentFolder, 30000, null, false, "e93ace6d-0b2d-4682-9078-8960374539bd", "")
            {
                _fnlnInfo = new RepoItemInfo(this, "Fnln", ".//input[#'fnln']", ".//input[#'fnln']", 30000, null, "57f64922-9297-4146-af7b-615bfc7009b8");
                _claimInfo = new RepoItemInfo(this, "Claim", ".//input[#'claim']", ".//input[#'claim']", 30000, null, "bcce7c69-2da6-42e2-b1e0-bd1743ac279d");
                _phonenumberInfo = new RepoItemInfo(this, "PhoneNumber", ".//input[#'phoneNumber']", ".//input[#'phoneNumber']", 30000, null, "64388fe4-8a3a-499e-9ca2-4e6a437a440f");
                _emailInfo = new RepoItemInfo(this, "Email", ".//input[#'email']", ".//input[#'email']", 30000, null, "df7f04da-3a5c-4179-8a55-4db4104c7839");
                _claimdetailsInfo = new RepoItemInfo(this, "ClaimDetails", ".//textarea[#'claim_details']", ".//textarea[#'claim_details']", 30000, null, "7c4a360f-de47-4565-a731-a9460ff3601b");
                _inputtagageInfo = new RepoItemInfo(this, "InputTagAge", ".//input[#'age']", ".//input[#'age']", 30000, null, "61db4798-5a4e-4c2a-83d5-202e18cb6740");
                _priceusdInfo = new RepoItemInfo(this, "Priceusd", ".//input[#'priceusd']", ".//input[#'priceusd']", 30000, null, "f84bbfa6-80be-462e-aee0-afb78fb92ec5");
                _priceuahInfo = new RepoItemInfo(this, "Priceuah", ".//input[#'priceuah']", ".//input[#'priceuah']", 30000, null, "8e8fcfe4-40d5-4f89-9ea9-0a60b6f56ca3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("e93ace6d-0b2d-4682-9078-8960374539bd")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("e93ace6d-0b2d-4682-9078-8960374539bd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Fnln item.
            /// </summary>
            [RepositoryItem("57f64922-9297-4146-af7b-615bfc7009b8")]
            public virtual Ranorex.InputTag Fnln
            {
                get
                {
                    return _fnlnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Fnln item info.
            /// </summary>
            [RepositoryItemInfo("57f64922-9297-4146-af7b-615bfc7009b8")]
            public virtual RepoItemInfo FnlnInfo
            {
                get
                {
                    return _fnlnInfo;
                }
            }

            /// <summary>
            /// The Claim item.
            /// </summary>
            [RepositoryItem("bcce7c69-2da6-42e2-b1e0-bd1743ac279d")]
            public virtual Ranorex.InputTag Claim
            {
                get
                {
                    return _claimInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Claim item info.
            /// </summary>
            [RepositoryItemInfo("bcce7c69-2da6-42e2-b1e0-bd1743ac279d")]
            public virtual RepoItemInfo ClaimInfo
            {
                get
                {
                    return _claimInfo;
                }
            }

            /// <summary>
            /// The PhoneNumber item.
            /// </summary>
            [RepositoryItem("64388fe4-8a3a-499e-9ca2-4e6a437a440f")]
            public virtual Ranorex.InputTag PhoneNumber
            {
                get
                {
                    return _phonenumberInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PhoneNumber item info.
            /// </summary>
            [RepositoryItemInfo("64388fe4-8a3a-499e-9ca2-4e6a437a440f")]
            public virtual RepoItemInfo PhoneNumberInfo
            {
                get
                {
                    return _phonenumberInfo;
                }
            }

            /// <summary>
            /// The Email item.
            /// </summary>
            [RepositoryItem("df7f04da-3a5c-4179-8a55-4db4104c7839")]
            public virtual Ranorex.InputTag Email
            {
                get
                {
                    return _emailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Email item info.
            /// </summary>
            [RepositoryItemInfo("df7f04da-3a5c-4179-8a55-4db4104c7839")]
            public virtual RepoItemInfo EmailInfo
            {
                get
                {
                    return _emailInfo;
                }
            }

            /// <summary>
            /// The ClaimDetails item.
            /// </summary>
            [RepositoryItem("7c4a360f-de47-4565-a731-a9460ff3601b")]
            public virtual Ranorex.TextAreaTag ClaimDetails
            {
                get
                {
                    return _claimdetailsInfo.CreateAdapter<Ranorex.TextAreaTag>(true);
                }
            }

            /// <summary>
            /// The ClaimDetails item info.
            /// </summary>
            [RepositoryItemInfo("7c4a360f-de47-4565-a731-a9460ff3601b")]
            public virtual RepoItemInfo ClaimDetailsInfo
            {
                get
                {
                    return _claimdetailsInfo;
                }
            }

            /// <summary>
            /// The InputTagAge item.
            /// </summary>
            [RepositoryItem("61db4798-5a4e-4c2a-83d5-202e18cb6740")]
            public virtual Ranorex.InputTag InputTagAge
            {
                get
                {
                    return _inputtagageInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputTagAge item info.
            /// </summary>
            [RepositoryItemInfo("61db4798-5a4e-4c2a-83d5-202e18cb6740")]
            public virtual RepoItemInfo InputTagAgeInfo
            {
                get
                {
                    return _inputtagageInfo;
                }
            }

            /// <summary>
            /// The Priceusd item.
            /// </summary>
            [RepositoryItem("f84bbfa6-80be-462e-aee0-afb78fb92ec5")]
            public virtual Ranorex.InputTag Priceusd
            {
                get
                {
                    return _priceusdInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Priceusd item info.
            /// </summary>
            [RepositoryItemInfo("f84bbfa6-80be-462e-aee0-afb78fb92ec5")]
            public virtual RepoItemInfo PriceusdInfo
            {
                get
                {
                    return _priceusdInfo;
                }
            }

            /// <summary>
            /// The Priceuah item.
            /// </summary>
            [RepositoryItem("8e8fcfe4-40d5-4f89-9ea9-0a60b6f56ca3")]
            public virtual Ranorex.InputTag Priceuah
            {
                get
                {
                    return _priceuahInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Priceuah item info.
            /// </summary>
            [RepositoryItemInfo("8e8fcfe4-40d5-4f89-9ea9-0a60b6f56ca3")]
            public virtual RepoItemInfo PriceuahInfo
            {
                get
                {
                    return _priceuahInfo;
                }
            }
        }

        /// <summary>
        /// The BookingFolder folder.
        /// </summary>
        [RepositoryFolder("63b8993f-1475-484b-8fbf-b266185b278a")]
        public partial class BookingFolder : RepoGenBaseFolder
        {
            RepoItemInfo _scheduleInfo;
            RepoItemInfo _submitInfo;
            RepoItemInfo _bookingInfo;

            /// <summary>
            /// Creates a new Booking  folder.
            /// </summary>
            public BookingFolder(RepoGenBaseFolder parentFolder) :
                    base("Booking", "", parentFolder, 0, null, false, "63b8993f-1475-484b-8fbf-b266185b278a", "")
            {
                _scheduleInfo = new RepoItemInfo(this, "Schedule", "/dom[@domain='192.168.56.3:5044']//div[#'app']/?/?/main//h1[@innertext='Schedule']", "/dom[@domain='192.168.56.3:5044']//div[#'app']//h1[@innertext='Schedule']", 30000, null, "b0c88105-519b-48e0-9aa2-da3f1e3eb581");
                _submitInfo = new RepoItemInfo(this, "Submit", "/dom[@domain='192.168.56.3:5044']//div[#'app']/?/?/main//form[@action='http://192.168.56.3:5044/booking']/button[@innertext='Submit']", "/dom[@domain='192.168.56.3:5044']//div[#'app']//button[@innertext='Submit']", 30000, null, "472d7a83-ccd0-4101-bd29-9076aa7ab259");
                _bookingInfo = new RepoItemInfo(this, "Booking", "/dom[@domain='192.168.56.3:5044']//div[#'app']/?/?/header/div/div[3]/nav//ul/li[2]/a[@innertext='Booking']", "/dom[@domain='192.168.56.3:5044']//div[#'app']//ul/li[2]/a[@innertext='Booking']", 30000, null, "3b4de602-7d7d-4f34-9e93-6d13ff0630d0");
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("63b8993f-1475-484b-8fbf-b266185b278a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Schedule item.
            /// </summary>
            [RepositoryItem("b0c88105-519b-48e0-9aa2-da3f1e3eb581")]
            public virtual Ranorex.H1Tag Schedule
            {
                get
                {
                    return _scheduleInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The Schedule item info.
            /// </summary>
            [RepositoryItemInfo("b0c88105-519b-48e0-9aa2-da3f1e3eb581")]
            public virtual RepoItemInfo ScheduleInfo
            {
                get
                {
                    return _scheduleInfo;
                }
            }

            /// <summary>
            /// The Submit item.
            /// </summary>
            [RepositoryItem("472d7a83-ccd0-4101-bd29-9076aa7ab259")]
            public virtual Ranorex.ButtonTag Submit
            {
                get
                {
                    return _submitInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Submit item info.
            /// </summary>
            [RepositoryItemInfo("472d7a83-ccd0-4101-bd29-9076aa7ab259")]
            public virtual RepoItemInfo SubmitInfo
            {
                get
                {
                    return _submitInfo;
                }
            }

            /// <summary>
            /// The Booking item.
            /// </summary>
            [RepositoryItem("3b4de602-7d7d-4f34-9e93-6d13ff0630d0")]
            public virtual Ranorex.ATag Booking
            {
                get
                {
                    return _bookingInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Booking item info.
            /// </summary>
            [RepositoryItemInfo("3b4de602-7d7d-4f34-9e93-6d13ff0630d0")]
            public virtual RepoItemInfo BookingInfo
            {
                get
                {
                    return _bookingInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
