///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace HealthPort_E2E
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("62d33aee-ae5c-4e33-80e8-067b3eb0eab0", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the HealthPort_E2ERepository repository.
        /// </summary>
        public static HealthPort_E2ERepository repo = HealthPort_E2ERepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Booking.Booking' at 80;15.", repo.Booking.BookingInfo, new RecordItemIndex(0));
            repo.Booking.Booking.Click("80;15");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HealthPort_e2e.Fnln' at 36;14.", repo.HealthPort_e2e.FnlnInfo, new RecordItemIndex(1));
            repo.HealthPort_e2e.Fnln.Click("36;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'alex Blob' with focus on 'HealthPort_e2e.Fnln'.", repo.HealthPort_e2e.FnlnInfo, new RecordItemIndex(2));
            repo.HealthPort_e2e.Fnln.PressKeys("alex Blob");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HealthPort_e2e.Claim' at 40;8.", repo.HealthPort_e2e.ClaimInfo, new RecordItemIndex(3));
            repo.HealthPort_e2e.Claim.Click("40;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aa bb cc' with focus on 'HealthPort_e2e.Claim'.", repo.HealthPort_e2e.ClaimInfo, new RecordItemIndex(4));
            repo.HealthPort_e2e.Claim.PressKeys("aa bb cc");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HealthPort_e2e.PhoneNumber' at 44;11.", repo.HealthPort_e2e.PhoneNumberInfo, new RecordItemIndex(5));
            repo.HealthPort_e2e.PhoneNumber.Click("44;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Add}{NumPad3}{NumPad7}' with focus on 'HealthPort_e2e.PhoneNumber'.", repo.HealthPort_e2e.PhoneNumberInfo, new RecordItemIndex(6));
            repo.HealthPort_e2e.PhoneNumber.PressKeys("{Add}{NumPad3}{NumPad7}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad5}{NumPad3}{NumPad3}{NumPad6}{NumPad7}{NumPad0}{NumPad2}{NumPad7}{NumPad2}{NumPad7}' with focus on 'HealthPort_e2e.PhoneNumber'.", repo.HealthPort_e2e.PhoneNumberInfo, new RecordItemIndex(7));
            repo.HealthPort_e2e.PhoneNumber.PressKeys("{NumPad5}{NumPad3}{NumPad3}{NumPad6}{NumPad7}{NumPad0}{NumPad2}{NumPad7}{NumPad2}{NumPad7}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HealthPort_e2e.Email' at 45;16.", repo.HealthPort_e2e.EmailInfo, new RecordItemIndex(8));
            repo.HealthPort_e2e.Email.Click("45;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'user' with focus on 'HealthPort_e2e.Email'.", repo.HealthPort_e2e.EmailInfo, new RecordItemIndex(9));
            repo.HealthPort_e2e.Email.PressKeys("user");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{RShiftKey down}@{RShiftKey up}gmail.com' with focus on 'HealthPort_e2e.Email'.", repo.HealthPort_e2e.EmailInfo, new RecordItemIndex(10));
            repo.HealthPort_e2e.Email.PressKeys("{RShiftKey down}@{RShiftKey up}gmail.com");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HealthPort_e2e.ClaimDetails' at 75;12.", repo.HealthPort_e2e.ClaimDetailsInfo, new RecordItemIndex(11));
            repo.HealthPort_e2e.ClaimDetails.Click("75;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'aaa bbb ccc ddd' with focus on 'HealthPort_e2e'.", repo.HealthPort_e2e.SelfInfo, new RecordItemIndex(12));
            repo.HealthPort_e2e.Self.EnsureVisible();
            Keyboard.Press("aaa bbb ccc ddd");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'HealthPort_e2e.InputTagAge' at 24;14.", repo.HealthPort_e2e.InputTagAgeInfo, new RecordItemIndex(13));
            repo.HealthPort_e2e.InputTagAge.MoveTo("24;14");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'HealthPort_e2e.InputTagAge' at 24;14.", repo.HealthPort_e2e.InputTagAgeInfo, new RecordItemIndex(14));
            repo.HealthPort_e2e.InputTagAge.MoveTo("24;14");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '50' with focus on 'HealthPort_e2e.InputTagAge'.", repo.HealthPort_e2e.InputTagAgeInfo, new RecordItemIndex(15));
            repo.HealthPort_e2e.InputTagAge.PressKeys("50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HealthPort_e2e.Priceusd' at 28;11.", repo.HealthPort_e2e.PriceusdInfo, new RecordItemIndex(16));
            repo.HealthPort_e2e.Priceusd.Click("28;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'HealthPort_e2e.Priceusd'.", repo.HealthPort_e2e.PriceusdInfo, new RecordItemIndex(17));
            repo.HealthPort_e2e.Priceusd.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '20' with focus on 'HealthPort_e2e.Priceusd'.", repo.HealthPort_e2e.PriceusdInfo, new RecordItemIndex(18));
            repo.HealthPort_e2e.Priceusd.PressKeys("20");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by -240 units.", new RecordItemIndex(19));
            Mouse.ScrollWheel(-240);
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'HealthPort_e2e.Priceuah' at 50;11.", repo.HealthPort_e2e.PriceuahInfo, new RecordItemIndex(20));
            repo.HealthPort_e2e.Priceuah.Click("50;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Booking.Submit' at 30;14.", repo.Booking.SubmitInfo, new RecordItemIndex(21));
            repo.Booking.Submit.Click("30;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (InnerText='Schedule') on item 'Booking.Schedule'.", repo.Booking.ScheduleInfo, new RecordItemIndex(22));
            Validate.AttributeEqual(repo.Booking.ScheduleInfo, "InnerText", "Schedule");
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
